### ISSUE TITLE
No module named 'btlewrap'

### ISSUE THREAD

**Issue by Jochen723** [open-homeautomation/miflora#102]
I get the following error:

/home/pi/miflora/demo.py --backend gatttool poll C4:7C:8D:61:57:A0
Traceback (most recent call last):
  File "/home/pi/miflora/demo.py", line 9, in <module>
    from btlewrap import available_backends, BluepyBackend, GatttoolBackend, PygattBackend
ImportError: No module named 'btlewrap'

**Comment by ChristianKuehnel** [comment]
the latest version of miflora depends on the btlewrap library. If you install miflora via pip (which is the recommended way), pip will also install this dependency for you. I just added this to the documentation:
https://github.com/open-homeautomation/miflora/blob/master/README.md#dependencies

**Comment by ChristianKuehnel** [comment]
old issue --> closing it

**Comment by Diluxshan** [comment]
I have the same error.
/home/pi/miflora/demo.py --backend gatttool poll C4:7C:8D:61:57:A0
Traceback (most recent call last):
File "/home/pi/miflora/demo.py", line 9, in 
from btlewrap import available_backends, BluepyBackend, GatttoolBackend, PygattBackend
ImportError: No module named 'btlewrap'

please guide, for import btlewrap file

**Comment by ChristianKuehnel** [comment]
did you try the solution above?

**Comment by Diluxshan** [comment]
yes, I try that... But still, I have a different error.

usage: demo.py poll [-h] mac
demo.py poll: error: the following arguments are required: mac
