### ISSUE TITLE
Home Assistant - "Unknow" States

### ISSUE THREAD

**Issue by schmidiij** [open-homeautomation/miflora#113]
we have found that with Hassio (Home Assistant) 0.73+ the sensor has the states "unknow"
i use a Raspberry Pi and the Docker Bluethoot BCM43xx (ResinOS) Addon. Any other bluethoot device work

[our "troubleshooting"](https://community.home-assistant.io/t/mi-flora-plant-sensor/29741/83?u=schmidij_ch)

**Comment by ChristianKuehnel** [comment]
Is this issue still open? From reading the forum, I'm not sure. The thread contains a lot of parallel discussions and I'm not sure which one you're refering to...

Do you have an error message for analysis?

**Comment by Schmidij** [comment]
with HassOS 1.9 (without BCM43xx (ResinOS) Addon - not nessesery) it's works :-)

**Comment by ChristianKuehnel** [comment]
ok, thx --> closing the ticket.
