### ISSUE TITLE
How does the misture sensor work?

### ISSUE THREAD

**Issue by GAZ082** [open-homeautomation/miflora#119]
Hey there. I've been trying to get info about this regards in several forums/pages and could not find any. Perhaps you guys will be able. In theory the value is in % (as commented in the code) but i did a simple test of putting the sensor in a glass of water and then drying it out with some paper towel.

The value i got under the glass of water is 70 and after well dried, 20. How is this supposed to work then? I understand that the lower value may be influenced by ambient moisture or another things, but the top value? I saturated it with moist in theory... dont know!

Any hit would be appreciated!

**Comment by ChristianKuehnel** [comment]
The electrical conductivity of tap water is probably not so good. If you
add a bit of salt (or fertilizer) you should probably get different values.
And my sensor does reports zero moisture if you just put it on the table.

However, I don't really care about the specifics. What I do is for my
plants: I defined a minimum moisture level per plant (between 15% an 30%,
depending on the plant) and I'm adding water whenever the moisture level is
below that. That works nicely. I never really bothered to check the
precision of the sensors...


Am Mi., 9. Jan. 2019 um 20:22 Uhr schrieb Gabriel Alejandro Zorrilla <
notifications@github.com>:

**Comment by GAZ082** [comment]
Thanks Christian! I'll do more rigorous testing, with salty water and will get a container and put some something to dry out the air inside it. Perhaps my ambient moisture is too high, dont know.

**Comment by ThomDietrich** [comment]
If you want to benchmark the sensor readings, pure water (or with salt) won't tell you as much. The sensor was probably never developed for this, therefore the reading is not meaningful. I second the opinion that relative changes should be more meaningful for you/the user.

If you want to get a better feeling for the value range, how about a measurement in dry (i.e. fresh) soil and in soaked soil. After this simple experiment you'll know your extremes in-between which you can scale your warning and alerting levels.

**Comment by GAZ082** [comment]
Yes, that's actually how i'm working now, normalizing in the 20-70 scale I got with "synthetic" benchmarks. What i'll do is redo the scale with desert-dry and flood-moisted soil and see how it works.

Thanks a lot!

**Comment by ThomDietrich** [comment]
I'm not sure about the real value of those measurements but I'd sure be interested in your results!

**Comment by ChristianKuehnel** [comment]
closing old issues
