### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc2' in file domoticz.py on line 69

### ISSUE THREAD

**Issue by kenand1970** [open-homeautomation/miflora#120]
I receive error message

SyntaxError: Non-ASCII character '\xc2' in file domoticz.py on line 69

I put # coding: utf8  to first line to domoticz.py but did not help.

**Comment by ChristianKuehnel** [comment]
By looking at the error message the problem seems to be in the file
domoticz.py

This file is not provided by miflora. Please contact someone who is working
on that file...

Am So., 13. Jan. 2019, 14:26 hat kenand1970 <notifications@github.com>
geschrieben:

**Comment by ChristianKuehnel** [comment]
closing old issues
