### ISSUE TITLE
Gatttool is deprecated

### ISSUE THREAD

**Issue by Kernald** [open-homeautomation/miflora#121]
While it's still available on most distributions, [gatttool has been officially deprecated by the BlueZ team two years ago](https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=b1eb2c4cd057624312e0412f6c4be000f7fc3617). Is there any plan to migrate to something else?

**Comment by ThomDietrich** [comment]
There are already other backends to choose from: https://github.com/open-homeautomation/miflora#backends
Fair point: The README could point out the deprecat'iveness of the gatttool backend. Feel free to add a PR discouraging the use of it.

**Comment by ChristianKuehnel** [comment]
Just added a comment to the README
