### ISSUE TITLE
BLE connection problems with firmware kernel 4.19

### ISSUE THREAD

**Issue by Markkuuss** [open-homeautomation/miflora#127]
With the latest firmware, which includes the Kernel 4.19, data transfer via Bluetooth is no longer possible after a few hours. Initially it works fine, but after a few hours no connection can be established - not only once but completely.

I have installed some older firmware versions. But it only works correctly with the last firmware commit, which still contains the Kernel 4.14:
https://github.com/Hexxeh/rpi-firmware/commit/a08ece3d48c3c40bf1b501772af9933249c11c5b

If someone still has the problem with a current firmware version. With the following command you can downgrade to the last 4.14 stable:
sudo BRANCH=stable rpi-update 45a2e771e7272781e62ae92322734c2b90e0268a
sudo reboot

**Comment by ChristianKuehnel** [comment]
Hi @Markkuuss ,

thank you for letting us know. Is there anything we should do about this? 
Do you want to add a comment to the documentation?

**Comment by Markkuuss** [comment]
Hi @ChristianKuehnel
I'm looking for a solution to run Miflora on a current firmware as well. Or at least hints where the error could be, e.g. if it is a firmware problem or if other software has to be adapted.

**Comment by antondollmaier** [comment]
I confirm this issue as well:

- it is solvable with `hciconfig hci0 down; sleep 5; hciconfig hci0 up` - but not every time.
- strace shows that `hciconfig down`  is stuck waiting on the bluetooth socket (AF_BLUETOOTH)
- incident happens after 12-24hr, sometimes already after 60min

Raspberry Pi 3, Raspbian Buster - issue already happened on Raspbian Stretch.

Issue seems not related to bluepy or miflora, but more with bluetooth in general.

**Comment by ChristianKuehnel** [comment]
Closing ticket as it's not so something that can be fixed in miflora.

**Comment by Markkuuss** [comment]
Where could this problem be addressed? Miflora doesn't work on a current Raspberry Pi anymore.
