### ISSUE TITLE
Beacon stops advertising when reading Mi Flora data

### ISSUE THREAD

**Issue by camfrout** [open-homeautomation/miflora#18]
Hi,

I am using a Raspberry Pi to read the data of the Mi Flora and it is working perfectly. I am now also trying to use the Raspberry Pi as an Beacon to monitor the presence of people in my house but I realised that whenever the Mi Flora data is read, my Raspberry Pi stops advertising and I have to run `sudo hciconfig hci0 leadv 0` again to be able to see my beacon.

Would it be a behavior of the bluetooth not allowing Beacon advertising and connection to a bluetooth device or is it something that could be fixed?

Ben

**Comment by open-homeautomation** [comment]
Hi,

I don't think, both will work on the same BT device.

Daniel
