### ISSUE TITLE
demo.py TimeoutExpired error

### ISSUE THREAD

**Issue by robmarkcole** [open-homeautomation/miflora#20]
When running demo.py

```
from subprocess import PIPE, Popen, TimeoutExpired

ImportError: cannot import name TimeoutExpired

```

**Comment by open-homeautomation** [comment]
Most likely you're using Python2. This library requires Python3.

**Comment by micksel** [comment]
I'm getting the same error on Python3, Raspbian/wheezy

**Comment by ChristianKuehnel** [comment]
@robmarkcole 
Do you still have the issue with the current master branch?

**Comment by ChristianKuehnel** [comment]
is this a duplicate of https://github.com/open-homeautomation/miflora/issues/29 ?

**Comment by ChristianKuehnel** [comment]
should be fixed with https://github.com/open-homeautomation/miflora/pull/61
