### ISSUE TITLE
Pygatt for additional platforms

### ISSUE THREAD

**Issue by flyingartichoke** [open-homeautomation/miflora#24]
Is there any chance of using pygatt as the BLE module so that both gatttool and BGAPI (i.e. linux and other computers with a BLED112 dongle) could be used to interface with the mi flora device?

**Comment by bhaap** [comment]
would really like this aswell. as im using mac for my home assistant platform and would really like to use my mi floras in that.

**Comment by ChristianKuehnel** [comment]
Habe a look at the proposal in https://github.com/open-homeautomation/miflora/pull/39
The idea is to support different Bluetooth backends for the different platforms. Once we agree on an architecture, feel free to add support for pygatt as well.

**Comment by ChristianKuehnel** [comment]
Done in #75
