### ISSUE TITLE
ImportError: cannot import name TimeoutExpired

### ISSUE THREAD

**Issue by micksel** [open-homeautomation/miflora#29]
I found my ID using : sudo hcitool lescan) 
C4:7C:8D:62:0C:81 Flower care

I edit demo.py with this but when I run it I get the following errors:
I edit demo.py with this but when I run it I get the following errors:
pi@domo1 ~ $ sudo /usr/bin/python3 /home/pi/domoticz/scripts/python/miflora/demo.py
pi@domo1 ~/domoticz/scripts/python/miflora/miflora/tests $ /usr/bin/python3 /home/pi/domoticz/scripts/python/miflora/demo.py
Traceback (most recent call last):
File "/home/pi/domoticz/scripts/python/miflora/demo.py", line 1, in <module>
from miflora.miflora_poller import MiFloraPoller, \
File "/home/pi/domoticz/scripts/python/miflora/miflora/miflora_poller.py", line 12, in <module>
from subprocess import PIPE, Popen, TimeoutExpired
ImportError: cannot import name TimeoutExpired

I can connect with gatttool -I and Connect 
pi@domo1 ~/domoticz/scripts/python $ gatttool -I
[                 ][LE]> connect c4:7c:8d:62:0c:81
Attempting to connect to c4:7c:8d:62:0c:81
Connection successful
Notification handle = 0x0021 value: 00
Notification handle = 0x0021 value: 00
Notification handle = 0x0021 value: 00
[c4:7c:8d:62:0c:81][LE]>
(gatttool:9429): GLib-WARNING **: Invalid file descriptor.

**Comment by micksel** [comment]
Running Python3 on a Pi3 with raspbian/wheezy

**Comment by ChristianKuehnel** [comment]
The ImportError indicates that python cannot find the TimeoutExpired error in the subprocess module. This should be part of every python installation...

I just tried to run the tests with Python 2.7 and I get the same error. Are you really sure that you're using Python3? Did you try ```python3 demo.py```?

**Comment by ThomDietrich** [comment]
A very common mistake and there is no nice way to avoid it.

**Comment by ChristianKuehnel** [comment]
Should be fixed with https://github.com/open-homeautomation/miflora/pull/61
