### ISSUE TITLE
Cross plattform compatibility

### ISSUE THREAD

**Issue by Benjamin3992** [open-homeautomation/miflora#3]
Would it be possible to use something like this: http://doc.qt.io/qt-5/qtbluetooth-le-overview.html to build an interface for only the BT communication to substitute the slightly annoying and not on windows avalible bluez libary?

**Comment by open-homeautomation** [comment]
While this might be possible in general, I won't work on this. If somebody wants to work on this and wants to submit a patch, I will look into it.
