### ISSUE TITLE
Unable to install using NPM

### ISSUE THREAD

**Issue by alandonegan** [open-homeautomation/miflora#30]
I am finding the following issue when trying to use NPM to install your library.

pi@raspberrypi:~/.node-red $ npm i https://github.com/open-homeautomation/miflora
npm ERR! addLocal Could not install /tmp/npm-3174-cbd0c9a8/git-cache-e9fd0e4fcfcf/3575b30e3b4e06d460a1088a8b96999dd328cbed
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "https://github.com/open-homeautomation/miflora"
npm ERR! node v4.8.2
npm ERR! npm  v2.15.11
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log

I've checked the log and it seems to be a carbon copy of what is written above.  I'm a bit of a noob with a lot of this so I could really do with a little help!

Please forgive me if I am pointing out an issue that is already raised or resolved elsewhere.

**Comment by open-homeautomation** [comment]
npm is a JavaScript package mager but this is a Python library. You can't use this with JavaScript.
