### ISSUE TITLE
Project status and future development

### ISSUE THREAD

**Issue by ThomDietrich** [open-homeautomation/miflora#34]
I'd like to ask if this project is still active.
A project of mine is dependent on this one and I would need the additions provided in the trivial PRs #32 and #33. Sadly there was no reaction over the course of one week. If this project is not actively maintained any longer, I would be forced to create a fork, not the path I want to go down. If the project is still active and you are e.g. enjoying your vacation right now I can of course wait.

Looking forward to a positive answer. Best regards!

**Comment by open-homeautomation** [comment]
This is a hobby project. While I will look into pull requests from time to time, I can't guarantee that I will do this within a few days.
