### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by marksev1** [open-homeautomation/miflora#4]
Can I connect to multiple Miflora's with your library?
And put data from multiple Miflora's into a json.

**Comment by usul27** [comment]
Yes, you can use multiple sensors. You need to implement the JSON stuff by yourself, the library does not create any JSON objects.

**Comment by marksev1** [comment]
Can you just write an example on how to get sensor values from multiple devices at once etc.?

**Comment by usul27** [comment]
Just look at the demo.py file and look through all your sensors.
