### ISSUE TITLE
project stale?

### ISSUE THREAD

**Issue by ChristianKuehnel** [open-homeautomation/miflora#41]
Dear maintainers,

I have the impression, that there is not much progress going on and that pull requests take quite long to get processed. Is that impression correct?

If so, what can we do about that? There are already some forks in place to work on new features.

Are you willing to take new maintainers?

br Christian

**Comment by open-homeautomation** [comment]
Yes, I'm willing to add new maintainers. Are you interested?

**Comment by ChristianKuehnel** [comment]
Yes, I'm interested, maybe also @ThomDietrich

**Comment by ThomDietrich** [comment]
Definitely, that would be a great step for the community 👍 Thanks for the consideration!

**Comment by ChristianKuehnel** [comment]
Thx!
