### ISSUE TITLE
Compatibility issues with new firmware version

### ISSUE THREAD

**Issue by ThomDietrich** [open-homeautomation/miflora#44]
Heads up!

https://github.com/ThomDietrich/miflora-mqtt-daemon/issues/10

Apparently the firmware version 3.1.8 will break compatibility. I did not do any tests yet myself.

**Comment by ChristianKuehnel** [comment]
just upgraded one of my sensors with the "flower care" app and for me it's still working in demo.py:

> Getting data from Mi Flora
> FW: 3.1.8
> Name: Flower care
> Temperature: 20.0
> Moisture: 41
> Light: 32
> Conductivity: 462
> Battery: 99

**Comment by ThomDietrich** [comment]
Thanks for testing. I'll contact the original reporter of the issue.
