### ISSUE TITLE
re-configure project in github to use TravisCI and Coverall

### ISSUE THREAD

**Issue by ChristianKuehnel** [open-homeautomation/miflora#52]
In other projects all pull requests are automatically built by [TravisCI](https://travis-ci.org/), so that you immediately see if the project is still working and all the coding conventions were followed. It would be nice to also have that here. I already provided an initial ```.travis.yml```.

It would also be nice to have [Coveralls](https://coveralls.io/) report the code coverage of the tests.

:warning: You probably need some special permissions in github to do this.

**Comment by fuzzmz** [comment]
For the TravisCI you should just enable the project in their web interface, the same for Coveralls.io.

**Comment by ChristianKuehnel** [comment]
Hey @open-homeautomation can you please do the steps proposed by @fuzzmz ? It seems that I do not have the permissions to do so...

**Comment by ChristianKuehnel** [comment]
Coveralls setup is now fixed (see https://github.com/open-homeautomation/miflora/issues/56). We're ready to enable TravisCI and Coveralls.

**Comment by ChristianKuehnel** [comment]
@open-homeautomation can you please enable TravisCI and Coveralls? I do not have the permissions to do this on this repo...

**Comment by open-homeautomation** [comment]
TravisCI and coveralls have been enabled for this repository

**Comment by ChristianKuehnel** [comment]
is working. thx.
