### ISSUE TITLE
Soil fertility instead of conductivity, bug when using brand new sensors.

### ISSUE THREAD

**Issue by Tristan79** [open-homeautomation/miflora#7]
Question Uno: 

Is the conductivity returned mislabeled? 
Looking at another reader it uses soil fertility instead of conductivity...

https://github.com/marcelrv/miflora/blob/master/miflora.py

Question Lasto:

I got a lot of these sensors, and two of them gave these errors when brand new from the package...
 
```
    print("Moisture: {}".format(poller.parameter_value(MI_MOISTURE)))
  File "/home/pi/miflora/miflora/miflora_poller.py", line 250, in parameter_value
    self._mac)
OSError: [Errno Could not read data from Mi Flora sensor %s] C4:7C:8D:62:2C:40

```

After placing them in soil for some time, it appears to work fine...,  it only happens with new ones straight from the package...

**Comment by open-homeautomation** [comment]
"Fertility" is not a physical value, the sensor measured the conductivity of the soil.

New sensors do not provide values, therefore you get this exception.

**Comment by ahmadihamid** [comment]
If we use android apps conductivity information "converted" to fertility, don't know the standard tho..
do you have it?
It would be nice if we could convert it too

**Comment by ChristianKuehnel** [comment]
@ahmadihamid 
This looks like a new question, please open a new issue. And can you be a bit more specific in the new issue:
* What you mean with "android apps conductivity information". Can you give an example? Screenshot?
* Convert what to what? 
* Why do you want to convert something?

The Xiaomi sensor delivers the conductivity in µS/cm as raw data. This is what the library outputs at the moment.

**Comment by ahmadihamid** [comment]
I think it's the same question..
The apps I mean is https://play.google.com/store/apps/details?id=com.huahuacaocao.flowercare
It interpret conductivity as fertility by some range of conductivity level
let's say x-y µS/cm
Below x is less fertile
Above y is over fertilized

![screenshot_20180108-030746](https://user-images.githubusercontent.com/10917804/34653757-3b9d15c0-f423-11e7-86b7-ae4df9a232a9.png)

Even more, it's specific for each type of plant.

**Comment by ChristianKuehnel** [comment]
Yes this is the same value you're getting via the "conductivity" value from the miflora library. You can directly take the min/max values from the app and check these with the library. The home assistant component [plant](https://home-assistant.io/components/plant/) does exactly that.

If it's about the wording conductivity vs. fertility:
What the sensor measures really is the electrical conductivity of the soil. From the conductivity you can guess how much fertilizer is in the soil. "Fertility" is a more complex property, and I'm not aware of any sensor technology that could measure that directly and certainly not for 12$. So I like conductivity better.

**Comment by ahmadihamid** [comment]
Hmm..
I'm not sure if I can get that value within the flowercare app. And I don't think it is fixed value like home assistant lib. But maybe I'm wrong. Thanks for poin me the lib, can't find it by myself before. 

Yap I'm aware of it, I'm a chemist and maybe overthught it.

**Comment by Mirarkitty** [comment]
Late comment, but I have a few of these sensors and I'm experimenting:

It seems useless to use the conductivity value directly; it's changing on soil moisture level as well as fertilizer (or probably salt and other electrolytes) amount in the soil.

![image](https://user-images.githubusercontent.com/3462581/114268667-82342680-9a02-11eb-8774-bcc12cb2137e.png)

(Came across this thread looking for something useful to do with the moisture and conductivity values, no luck yet. Using them raw isn't great.)

![image](https://user-images.githubusercontent.com/3462581/114268692-be678700-9a02-11eb-985c-c3f8de76d880.png)
