### ISSUE TITLE
Support for -1 degrees and lower

### ISSUE THREAD

**Issue by jongerenchaos** [open-homeautomation/miflora#71]
I use this mi flora product outside. But when the temperature is under the 0 degrees the software gives a reading error. I think this product measure also lower than 0 degrees... Can anybody resolve this?

**Comment by ChristianKuehnel** [comment]
Hi @jongerenchaos ,

this issues should have been fixed with version 0.2.0 we released a few days ago. Can you please check with the new version?

**Comment by jongerenchaos** [comment]
Thanks!

For now it won't work with this domoticz file: https://github.com/Tristan79/miflora/blob/master/domoticz.py

**Comment by ChristianKuehnel** [comment]
Which version of miflora are you using?

```
pip show miflora
```

**Comment by ChristianKuehnel** [comment]
no reaction for 1 month -> closing issue
