### ISSUE TITLE
Coveralls - disable comments

### ISSUE THREAD

**Issue by ChristianKuehnel** [open-homeautomation/miflora#76]
Hey @open-homeautomation,

can you please set "LEAVE COMMENTS?" in the coveralls configuration to disabled? This way we can avoid the many ugly postings on pull requests: https://github.com/open-homeautomation/miflora/pull/73#issuecomment-356722372

**Comment by open-homeautomation** [comment]
I can't find this setting in coveralls (I don't see any settings at all in coveralls). Can you tell me where this is?

**Comment by ChristianKuehnel** [comment]
It took me some time to find:
1. go to coveralls
2. on the left, from the menu, select "repos"
3. the pick the repo you want to change
4. on the left select settings
5. then you can disable "leave comment"

**Comment by open-homeautomation** [comment]
This has been changed.
