### ISSUE TITLE
I'm thinking if you can write another one supporting for the Mi BLE Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by datoutie** [open-homeautomation/miflora#82]
website:  https://www.mi.com/mj-humiture/
Thanks.

**Comment by ChristianKuehnel** [comment]
I haven't seen one of those sensors, yet. But I guess if there is an app, we can probably also reverse engineer the protocol. If you can send me such a sensor I'll give it a try.

**Comment by fanthos** [comment]
I had some research on the sensor. Using `OpenMQTTGateway` on my ESP32, and found that the new sensor using the same tech with flora sensor, but different data format.

**Comment by ChristianKuehnel** [comment]
I think it does not make sense to add this to the miflora library, as it's a different protocol and a different device.

What might make sense is to share the BluetoothBackend wrappers, as you might also need that for this sensor...

**Comment by sandrisj** [comment]
You can use esp32 for this particular device. See here: https://www.youtube.com/watch?v=gyZjGOgDIRU
