### ISSUE TITLE
When Temperature is below zero very high values are returned (<6553.5)

### ISSUE THREAD

**Issue by lionhe1966** [open-homeautomation/miflora#87]
During these cold nights my sensor measure temperatures below zero. The MiFlora App gives the right temperature, while the miflora MQTT-daemon which is based on miflora returns
{"conductivity": 1397, "moisture": 35, "temperature": 6553.5, "light": 66, "battery": 98}

This is clearly due to the fact that the temperature is a SIGNED integer while the Miflora-daemon interprets it as an UNSIGNED integer.

**Comment by ChristianKuehnel** [comment]
This issue should have been fixed for some time. Please update to the latest version of miflora.
